### ISSUE TITLE
State is hard-coded

### ISSUE THREAD

**Issue by SirBryan** [charuwts/UCRM-Client-Signup-Form#1]
I was playing with the plugin this form belongs to and found the state field isn't an option, and is hard-coded to Colorado (CO).  Tracked it down to the compiled JS.

(Upon further inspection I can see you have State/Country commented out. This is less of a "complaint" of an issue, but a "heads up" to others who may wish to check it out.)

**Comment by charuwts** [comment]
Thanks for the note @SirBryan 

This is correct, I have a partial implementation of the ability to select the state but I did not realize it was still hard coded in. I'll work on polishing this off in the next day or two.

One downside is states are only available to United States and Canada in UCRM currently.
